#font
font_family JetBrainsMono Nerd Font Mono
font_size 16.0

#color
#foreground #000000
#background #D3D3D3
foreground #EEEEEE
background #000000
background_opacity 0.55

#text cursor
cursor #8B008B

#tab bar
tab_bar_background #000000

