# 0. Terminate process
leftctrl+q : EXIT

# 1. Trigger virtual mouse mode

# 1-1. For standard keyboard layout
f18 : LINEAR_MODE
f18+leftshift : LOGARITHMIC_MODE
f18+c : SCROLL_MODE

# 1-2. For HHKB layout
#leftalt : LINEAR_MODE
#leftalt+leftshift : LOGARITHMIC_MODE
#leftalt+c : SCROLL_MODE

# 2. Move cursor or scroll

# 2-1. Intuitive
i : MOVE_UP
k : MOVE_DOWN
j : MOVE_LEFT
l : MOVE_RIGHT

# 2-2. Vim
# k : MOVE_UP
# j : MOVE_DOWN
# h : MOVE_LEFT
# l : MOVE_RIGHT

# 3. Mouse click
space : CLICK_LEFT
semicolon : CLICK_RIGHT
