# Process
leftctrl+q : EXIT
leftmeta+leftctrl+r : RESET

# Trigger virtual mouse mode
leftmeta : LINEAR_MODE
leftmeta+leftshift : LOGARITHMIC_MODE
leftmeta+c : SCROLL_MODE

# Move cursor or scroll
i : MOVE_UP
k : MOVE_DOWN
j : MOVE_LEFT
l : MOVE_RIGHT

# Mouse click
space : CLICK_LEFT
semicolon : CLICK_RIGHT
