# switch step mode
leftmeta : LINEAR_MODE
leftmeta+leftshift : LOGARITHMIC_MODE

# move cursor
i : MOVE_UP
k : MOVE_DOWN
l : MOVE_RIGHT
j : MOVE_LEFT

# click
space : CLICK_LEFT
semicolon : CLICK_RIGHT

# scroll
leftalt+i : SCROLL_UP
leftalt+k : SCROLL_DOWN

