# ThinkPad build-in keyboard -> HHKB layout 
leftalt -> leftmeta
leftmeta -> leftalt
capslock -> leftctrl

rightalt -> macro
rightalt + j -> left
rightalt + l -> right
rightalt + i -> up
rightalt + k -> down

#rightshift -> macro
rightshift + tab -> capslock
