# ThinkPad build-in keyboard -> HHKB layout 
leftalt -> leftmeta
leftmeta -> leftalt
capslock -> leftctrl

pagedown -> macro
pagedown + semicolon -> left
pagedown + apostrophe -> right
pagedown + leftbrace -> up
pagedown + slash -> down

pagedown + tab -> capslock
