# Grab mode trigger keys
grab_linear : false
grab_logarithmic : true
grab_scroll : true

# Cursor step size
step_size_x : 256
step_size_y : 256
min_step_size_x : 5
min_step_size_Y : 5

# Wheel scroll distance
scroll_dist_x : 256
scroll_dist_y : 256
min_scroll_dist_x : 16
min_scroll_dist_y : 16
