# Grab mode trigger keys
grab_linear : false
grab_logarithmic : true
grab_scroll : true

# Cursor step size
step_size_x : 128
step_size_y : 128

# Wheel scroll distance
scroll_dist_x : 2
scroll_dist_y : 2
