# 0. Process
leftctrl+q : EXIT
f22+leftctrl+r : RESET

# 1. Trigger virtual mouse mode
f22 : LINEAR_MODE
f22+leftshift : LOGARITHMIC_MODE
f22+c : SCROLL_MODE

# 2. Move cursor or scroll
i : MOVE_UP
k : MOVE_DOWN
j : MOVE_LEFT
l : MOVE_RIGHT

# 3. Mouse click
space : CLICK_LEFT
semicolon : CLICK_RIGHT